GET http://localhost:5001
###

POST http://localhost:5001/api/admin/register
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "nrongerjngoenrger"
}

###

POST http://localhost:5001/api/examiner
Content-Type: application/json

{
    "firstname": "Jackson",
    "lastname": "Hayes",
    "email": "jackson@email.com",
    "password": "trutrutrutrutrutru133#"
}

###

GET http://localhost:5001/api/examiner/182146a5-3cc9-4841-9e03-29ff298b6e3e


###
DELETE  http://localhost:5001/api/examiner/182146a5-3cc9-4841-9e03-29ff298b6e3e
