GET http://localhost:5001
###

POST http://localhost:5001/api/admin/register
Content-Type: application/json

{
    "email": "omonuwafortunate@gmail.com",
    "password": "F0rtun@te0m0nuw@"
}

###

POST http://localhost:5001/api/examiner
Content-Type: application/json

{
    "firstname": "Jackson",
    "lastname": "Hayes",
    "email": "jackson30@email.com",
    "password": "trutrutrutrutrutru133#"
}

###

GET http://localhost:5001/api/examiner/16aa027d-1c37-4d50-b34e-eb92aae0ae2c


###
DELETE  http://localhost:5001/api/examiner/182146a5-3cc9-4841-9e03-29ff298b6e3e


###
POST http://localhost:5001/api/exam/bab36b65-b024-491a-a9ce-e4449290ee67
Content-Type: application/json

{
    "exam": {
        "title": "Mathematics",
        "description": "Mathematics exam",
        "subject": "Mathematics",
        "stipulatedTime": 60,
        "enforceTimeLimit": true,
        "questions": [
            {
                "text": "What is 2 + 2?",
                "options": [
                    {
                        "text": "4",
                        "isCorrect": true
                    },
                    {
                        "text": "5",
                        "isCorrect": false
                    }
                ]
            },
            {
                "text": "What is 2 + 3?",
                "options": [
                    {
                        "text": "4",
                        "isCorrect": false
                    },
                    {
                        "text": "5",
                        "isCorrect": true
                    }
                ]
            }
        ]
    }
}
###
DELETE http://localhost:5001/api/exam/b2bb457a-7700-4aea-9b53-fb0d1631fca1

###
GET http://localhost:5001/api/exam/b2bb457a-7700-4aea-9b53-fb0d1631fca1